baseURL = "https://blog.erik.is/"
languageCode = "en-us"
title = "blog.erik.is"
subtitle = "Erik Nomitch"
theme = "hello-friend"
copyright = "Erik Nomitch"
keywords = ""
menuMore = "Show more"
writtenBy = "Written by"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
minuteReadingTime = "min read"
dateFormatSingle = "2006-01-02"
dateFormatList = "2006-01-02"

[params]
  [params.logo]
    logoText = "blog.erik.is"
    logoHomeLink = "/"
    alt = "blog.erik.is / index"

[languages]
  [languages.en]
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "guides"
        url = "/guides"
